### ISSUE TITLE
CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)

### ISSUE THREAD

**Issue by 257556227** [albertwy/SWRM#2]
Dear Authors,
   - I put the datasets and pretraining BERT files in accordance with the corresponding path according to Readme, and then run the run.py, however i got **'CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)'** error in _'  File "/SWRM/models/subNets/BertTextEncoder.py", line 56, in forward
    last_hidden_states = self.model(input_ids=input_ids,'._ 
   - The specific location is as follows:
   /pytorch/aten/src/ATen/native/cuda/Indexing.cu:662: indexSelectLargeIndex: block: [633,0,0], thread: [64,0,0] **Assertion `srcIndex < srcSelectDimSize` failed.**
     File "/SWRM/models/singleTask/SWRM.py", line 81, in forward
    last_seq_hiddens = self.gate_network(text)
  File "/SWRM/models/subNets/BertTextEncoder.py", line 56, in forward
    last_hidden_states = self.model(input_ids=input_ids,
   - Since I run it with single GPU, I try to reduce mlm_bz, but the problem has not changed.(batchsize in BertTextEncoder is 16, I don't know how to modify the batchsize here)
   - When turning to the CPU-only machine, there were similar errors. **‘IndexError: index out of range in self’** So, someone else can talk me why?

**Comment by albertwy** [comment]
Thanks for your attention!

mlm_bz is the batch size for the sentiment word position detection.  Just ignore it.  You can find the related code at https://github.com/albertwy/SWRM/blob/main/trains/singleTask/SWRM.py#L116.

We have done it and provide the .pkl files(such as https://github.com/albertwy/SWRM/blob/main/sentiment_word_map_ibm_asr_train.pkl).

If you want to change the batch size for the regression model, you can change this line.  (https://github.com/albertwy/SWRM/blob/main/config/config_regression.py#L184)

As for the ‘IndexError: index out of range in self’ error, I find that I specified the wrong path for the pre-trained bert model. Sorry for that, I have fixed it. 

Thank you again!

**Comment by 257556227** [comment]
It helps me. Thanks. I'll close this issue.
